apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata: { name: farmpulse, namespace: argocd }
spec:
  description: FarmPulse platform applications
  sourceRepos: [https://github.com/prabhat-roy/FarmPulse.git]
  destinations:
    - { namespace: farmpulse,    server: https://kubernetes.default.svc }
    - { namespace: 'farmpulse-*', server: https://kubernetes.default.svc }
  clusterResourceWhitelist:    [{ group: '*', kind: '*' }]
  namespaceResourceWhitelist:  [{ group: '*', kind: '*' }]
