exposureType: ingress
expose:
  ingress:
    hosts: { core: harbor.farmpulse.internal }
    annotations: { kubernetes.io/ingress.class: traefik }
externalURL: https://harbor.farmpulse.internal
persistence:
  persistentVolumeClaim:
    registry: { storageClass: gp3, size: 2Ti }
trivy: { enabled: true }
chartmuseum: { enabled: true }
